
defaultEntryPoints = ["http"]

# debug UI
[web]
  address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"

[consulCatalog]
  endpoint = "172.17.0.1:8500"
  constraints = [ "tag==traefik" ]

[file]

[frontends]
  [frontends.traefikstats]
  backend = "traefikstats"
    [frontends.traefikstats.routes.default]
    rule = "Host:traefikstats.dev-laptop.xs.fi"

  [frontends.consul]
  backend = "consul"
    [frontends.consul.routes.default]
    rule = "Host:consul.dev-laptop.xs.fi"

[backends]
  [backends.traefikstats]
    [backends.traefikstats.servers.default]
    url = "http://127.0.0.1:8080"

  [backends.consul]
    [backends.consul.servers.default]
    url = "http://172.17.0.1:8500"
