
defaultEntryPoints = ["public_http", "public_https"]

# admin/debug UI
[web]
  address = ":8080"

# entrypoints are basically TCP ports which the dynamic frontends will attach to
[entryPoints]
  [entryPoints.public_http]
  address = ":80"

  [entryPoints.public_https]
  address = ":443"
    [entryPoints.public_https.tls]
      [[entryPoints.public_https.tls.certificates]]
      CertFile = "/etc/traefik/ssl_certs/public_https.crt"
      KeyFile = "/etc/traefik/ssl_certs/public_https.key"

  [entryPoints.backoffice]
  address = ":9001"
    [entryPoints.backoffice.tls]
      [[entryPoints.backoffice.tls.certificates]]
      CertFile = "/etc/traefik/ssl_certs/public_https.crt"
      KeyFile = "/etc/traefik/ssl_certs/public_https.key"
  [entryPoints.backoffice.auth.basic]
  # replaced dynamically from /run.sh
  users = #BACKOFFICE_USERS

[docker]
  endpoint = "unix:///run/docker.sock"

  # we're always explicitly defining the frontend rule, so we don't need default domain
  domain = ".invalid"

  # pick up updates
  watch = true

  # use Docker Swarm API to list tasks (= cluster-wide) instead of containers (= host-specific)
  swarmmode = true

  # require traefik.enable=True
  exposedbydefault = false
