
defaultEntryPoints = ["public_http"]

# debug UI
[web]
  address = ":8080"

[entryPoints]
  [entryPoints.public_http]
  address = ":80"

  [entryPoints.backoffice]
  address = ":9001"
  [entryPoints.backoffice.auth.basic]
  users = #BACKOFFICE_USERS

[docker]
  endpoint = "unix:///run/docker.sock"

  # we're always explicitly defining the frontend rule, so we don't need default domain
  domain = ".invalid"

  # pick up updates
  watch = true

  # use Docker Swarm API to list tasks (= cluster-wide) instead of containers (= host-specific)
  swarmmode = true

  # require traefik.enable=True
  exposedbydefault = false
