
defaultEntryPoints = ["http"]

# debug UI
[web]
  address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"

[docker]
  endpoint = "unix:///run/docker.sock"

  # we're always explicitly defining the frontend rule, so we don't need default domain
  domain = ".invalid"

  # pick up updates
  watch = true

  # use Docker Swarm API to list tasks (= cluster-wide) instead of containers (= host-specific)
  swarmmode = true

  # require traefik.enable=True
  exposedbydefault = false

[file]

[frontends]
  [frontends.traefikstats]
  backend = "traefikstats"
    [frontends.traefikstats.routes.default]
    rule = "Host:traefikstats.dev-laptop.xs.fi"

[backends]
  [backends.traefikstats]
    [backends.traefikstats.servers.default]
    url = "http://127.0.0.1:8080"
